name: theAIE
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pytorch
  - pip
  - pip:
      - openai
      - python-dotenv
      - jsonschema
      - fastapi
      - uvicorn[standard]
